"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from decouple import config, Csv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

# Usar autenticação real do Firebase mesmo em modo DEBUG
FIREBASE_REAL_AUTH = config('FIREBASE_REAL_AUTH', default=True, cast=bool)

# Configuração de hosts permitidos
ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'viccoin-backend.onrender.com',
    'viccoin.onrender.com',
    'Hencheo.pythonanywhere.com',  # Substitua 'seuusuario' pelo seu nome de usuário do PythonAnywhere
]


# Application definition

INSTALLED_APPS = [
    # Removendo apps padrão do Django que dependem de banco de dados
    # 'django.contrib.admin',
    # 'django.contrib.auth',
    # 'django.contrib.contenttypes',
    # 'django.contrib.sessions',
    # 'django.contrib.messages',  # Removido para evitar dependência de sessões
    'django.contrib.staticfiles',
    
    # Third-party apps
    'rest_framework',
    'corsheaders',
    
    # Local apps
    'firebase_auth',
    'firestore_api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Para servir arquivos estáticos no Render
    # 'django.contrib.sessions.middleware.SessionMiddleware', # Removido, não usaremos sessões
    'corsheaders.middleware.CorsMiddleware',  # Para permitir CORS
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    # 'django.contrib.auth.middleware.AuthenticationMiddleware', # Removido, usaremos autenticação Firebase
    # 'django.contrib.messages.middleware.MessageMiddleware', # Removido, não usaremos mensagens
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Configuração de CORS
CORS_ALLOWED_ORIGINS = [
    'https://viccoin-app.web.app',
    'https://viccoin-app.firebaseapp.com',
    'http://localhost:8080',
    'http://localhost:3000',
    'http://localhost:19000',
    'http://localhost:19006',
    'exp://192.168.0.176:8081',
    'exp://192.168.0.176:8082',  # Adicionando a porta 8082 também
    'https://exp.host',  # Para o Expo publicado
    'exp://*',          # Qualquer URL de Expo
]

# Em desenvolvimento e produção, permite todas as origens para garantir compatibilidade
CORS_ALLOW_ALL_ORIGINS = True

# Configurações adicionais de CORS
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Permitir todos os cabeçalhos nos pedidos
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'access-control-allow-origin',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                # 'django.contrib.auth.context_processors.auth', # Removido
                # 'django.contrib.messages.context_processors.messages', # Removido
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database - Usando configuração dummy pois usamos Firestore em vez de banco relacional
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.dummy',
    }
}


# Auth password validators - mantidos para compatibilidade, mas não usados com Firebase Auth
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configurações do REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'firebase_auth.authentication.FirebaseAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'UNAUTHENTICATED_USER': None,  # Não usar modelo de usuário do Django
    # Endpoints públicos
    'UNAUTHENTICATED_TOKEN_ENDPOINTS': [
        'api/categorias/',
        'api/health/',
    ],
}

# Configurações do Firebase - Podemos usar arquivo ou variáveis de ambiente
FIREBASE_CREDENTIALS_PATH = os.path.join(BASE_DIR, 'credentials', 'firebase-credentials.json')

# Habilitar logging para depuração
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'firebase_auth': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'firestore_api': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
