services:
  - type: web
    name: viccoin-backend
    env: python
    buildCommand: cd backend && pip install -r requirements.txt && pip install firebase-admin numpy && python manage.py collectstatic --noinput
    startCommand: cd backend && PYTHONPATH=/opt/render/project/src/backend gunicorn --chdir /opt/render/project/src/backend core.wsgi:application
    envVars:
      - key: SECRET_KEY
        value: 5-77qdC_ZF8WbyX6jFkZEpWYLxrA0c7_NrB2fzGvqah-IFdFvDrbLWNgpdZHMSvhGsE
      - key: DEBUG
        value: false
      - key: FIREBASE_REAL_AUTH
        value: true
      - key: ALLOWED_HOSTS
        value: "localhost,127.0.0.1,viccoin-backend.onrender.com,viccoin.onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://viccoin.onrender.com"
      # Firebase credenciais
      - key: FIREBASE_TYPE
        value: "service_account"
      - key: FIREBASE_PROJECT_ID
        value: "viccoin-2b851"
      - key: FIREBASE_PRIVATE_KEY_ID
        value: "9e8a0211cbcc14ba911f7373947e380cf67ea21b"
      - key: FIREBASE_PRIVATE_KEY
        value: "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCd97TC9A+ubYbb\nSRhpVXuFxBtjA8urTeyi8yNwZKFTUtRVrH7ZcT1L1qWzgWiemAXVdtu28DuiuuJr\nPM3JrxR5nNs68nV8ARoRkbfVeLljvHKrjNEF++UP6WA3HrGCnAo4FywDG+5pl+GO\nQ8XubRxC4DJeU9Iwz9hB7ZXF9ukqg18FKMDRJPMLsT7UNKqvULA84Ts088LI3BlP\negOTS3rTAZAEyh4Dw6sLyOdC101FCJPF0s0bjgI7y6HGVUz/Sw+5sx7RqRz4hV3Z\ny2c0NOx7S81dUXZTzSMLqt/cxsOBXYV26ZU5Ejtvz7u/WwJAeYOBQ9xxPblkik4q\nY3tnYiETAgMBAAECggEABGK5qoXzH4Eb8t+bJWWBqeuRZRTYZTejH70HWVn53qHY\nkk5ZMTlDHeVmMU8g8/I9izkjDXeq+DAfFCIahoRtWZkAvyi3GUvAiQdWJr+Uyg+T\n0W516Sgeqmvsx2r7O6iQYhFGoAl4+4aDdRstlhqCY9rsmxDRr5g9pUru0xGxVIRJ\nBrhaoqieHBgj3H31KLEvcX7OrhX8X5Hm9wMkZrlvWC4XNZ5j8ZD0/6Q5IY7dZXAd\n2l/pTf2gUSx2sCem5MGlXP0UCQz11LecKF62jGliZMatXGo9SnO8HYry8zxpiQbE\nYimsb4Am5Q9vNzdiRw784DxEpUMF6SlbUtOmk2K+VQKBgQDL/HeeldUpwE99SCff\nNnlXeeLuSL2U/+HkIffb6oAUAJhGXcX+Qu/HzHyUiiVghMsQxfhzKKDn2B4giMcY\n4yechvrxNusLqafpQfeGhBh7iGeIfrxrJ0dkitOUy8QPNvZ5SE1s5g9B3uwJ4B7r\net5V5XjT1C2DgmEVaD18KLt+ZQKBgQDGP0yyF/X7tHK3ZfJAgv5NDu9coCQa2nSc\nLkRmkfRDxZ3snx97JIa0qZBz9PwUPpXUQPV7GNqg2r02TVYO6H8rEkv6X0xUd2T3\nF+GJcAhZSflIucaKVoRl5RRJbCHCpoRlUvjvGyRnxeLh1C0I/dkYMOmm9wQWD0mV\nl99PXftOFwKBgQCT8ewgDLOpsFz2lFq2vZ+MHk7EW+WEJ4ICH9DQo2d5GmVWw7RS\nEOIvmtPQN9GcCzPsWmkzvIfXHxvapNkh575W/F8Mi7Q1pTqvJrULzsqi7e+JQ8IM\nRVS2SynhhVgRYN+qXxIopULzl2bCUtaaG2ceDWxw1jacZvdau1u8rR4vMQKBgBqb\njFOq25z4zxzGVglKi48UHhQ0eiQQhe4gV5XcqQgfkd6cTMFeWaYNzBGEJAEjlUBz\np37qCw3jzdln79D4a3kAb6oe+EOt8qMnVWH442X4g7i7FmaizgpPALYKCU3yw3pF\n9JtC7VPwP09IBvNZ/rU8e1+pb6b2Tk4BoDsqxfvpAoGAfWdKN5Yvw96rRGEEJV63\nmW9ISbvPfiBigY7PDgYM3m9HS+r9+qzbK0I1evLDo2F5JCpA0mvV5LR3zn4dmyEN\nsgsr0MkxI4jUOV1qFTd2zFgy6It8PnbxIBe6kRv+lwIE2lFpPyTxyttVAwlE54mH\ngHOmyO4np0vAOzS/4Agb6CI=\n-----END PRIVATE KEY-----\n"
      - key: FIREBASE_CLIENT_EMAIL
        value: "firebase-adminsdk-fbsvc@viccoin-2b851.iam.gserviceaccount.com"
      - key: FIREBASE_CLIENT_ID
        value: "102246113881671193944"
      - key: FIREBASE_AUTH_URI
        value: "https://accounts.google.com/o/oauth2/auth"
      - key: FIREBASE_TOKEN_URI
        value: "https://oauth2.googleapis.com/token"
      - key: FIREBASE_AUTH_PROVIDER_X509_CERT_URL
        value: "https://www.googleapis.com/oauth2/v1/certs"
      - key: FIREBASE_CLIENT_X509_CERT_URL
        value: "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40viccoin-2b851.iam.gserviceaccount.com"
      - key: FIREBASE_UNIVERSE_DOMAIN
        value: "googleapis.com"
      - key: PYTHON_VERSION
        value: 3.11.0 