// Constantes para autenticação
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

// Constantes para transações
export const FETCH_TRANSACOES_REQUEST = 'FETCH_TRANSACOES_REQUEST';
export const FETCH_TRANSACOES_SUCCESS = 'FETCH_TRANSACOES_SUCCESS';
export const FETCH_TRANSACOES_FAILURE = 'FETCH_TRANSACOES_FAILURE';

export const ADD_TRANSACAO_REQUEST = 'ADD_TRANSACAO_REQUEST';
export const ADD_TRANSACAO_SUCCESS = 'ADD_TRANSACAO_SUCCESS';
export const ADD_TRANSACAO_FAILURE = 'ADD_TRANSACAO_FAILURE';

// Constantes para resumo financeiro
export const FETCH_RESUMO_REQUEST = 'FETCH_RESUMO_REQUEST';
export const FETCH_RESUMO_SUCCESS = 'FETCH_RESUMO_SUCCESS';
export const FETCH_RESUMO_FAILURE = 'FETCH_RESUMO_FAILURE';

// Constantes para relatórios
export const FETCH_RELATORIO_REQUEST = 'FETCH_RELATORIO_REQUEST'; 
export const FETCH_RELATORIO_SUCCESS = 'FETCH_RELATORIO_SUCCESS';
export const FETCH_RELATORIO_FAILURE = 'FETCH_RELATORIO_FAILURE';

// Constantes para categorias
export const SET_CATEGORIAS = 'SET_CATEGORIAS';
export const ADD_CATEGORIA = 'ADD_CATEGORIA'; 